"""Update encoding string length

Revision ID: 8db613644ff6
Revises: 66f77abff586
Create Date: 2025-10-03 03:11:39.331600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8db613644ff6'
down_revision: Union[str, Sequence[str], None] = '66f77abff586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('face_encodings', 'encoding',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('face_encodings', 'encoding',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
