"""add status column into companies

Revision ID: f384ebd46d5c
Revises: c2f1d33ab1df
Create Date: 2025-10-06 14:50:56.348567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f384ebd46d5c'
down_revision: Union[str, Sequence[str], None] = 'c2f1d33ab1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('status', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'status')
    # ### end Alembic commands ###
